name: gtk_flutter
description: Get to know Firebase with Flutter
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=2.17.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^1.0.0 # new
  firebase_auth: ^1.0.0
  provider: ^5.0.0
  cupertino_icons: ^1.0.2
  google_fonts: ^3.0.1
  firebase_core: ^1.20.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/codelab.png
